param(
    [string]$OutputDir = "./docs/api",
    [string]$ApiProjectPath = "src/YLproxy.Api"
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
Write-Host "[docs] Output directory: $OutputDir"

# Read version from Directory.Build.props
$version = "0.2.0"
$propsPath = "Directory.Build.props"
if (Test-Path $propsPath) {
    $content = Get-Content $propsPath -Raw
    $match = [regex]::Match($content, '<Version>(.+?)</Version>')
    if ($match.Success) {
        $version = $match.Groups[1].Value
    }
}
Write-Host "[docs] Version: $version"

# Copy XML documentation
$apiOutput = "$ApiProjectPath/bin/Release/net10.0"
if (Test-Path "$apiOutput/YLproxy.Api.xml") {
    Copy-Item "$apiOutput/YLproxy.Api.xml" "$OutputDir/YLproxy.Api.xml" -Force
    Write-Host "[docs] Copied YLproxy.Api.xml"
}

# Write index.html using stream writer to avoid here-string issues
$stream = [System.IO.StreamWriter]::new("$OutputDir/index.html", $false, [System.Text.Encoding]::UTF8)
$stream.Write('<!DOCTYPE html>')
$stream.Write([Environment]::NewLine)
$stream.Write('<html lang="zh-CN">')
$stream.Write([Environment]::NewLine)
$stream.Write('<head>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <meta charset="UTF-8">')
$stream.Write([Environment]::NewLine)
$stream.Write('  <meta name="viewport" content="width=device-width, initial-scale=1.0">')
$stream.Write([Environment]::NewLine)
$stream.Write('  <title>YLproxy API Documentation</title>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <style>')
$stream.Write([Environment]::NewLine)
$stream.Write('    * { margin: 0; padding: 0; box-sizing: border-box; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    body { font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-bottom: 20px; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    h2 { color: #2c3e50; margin-top: 30px; margin-bottom: 10px; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .endpoint { background: #f8f9fa; padding: 12px 16px; margin: 8px 0; border-radius: 6px; border-left: 4px solid #3498db; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .method { display: inline-block; padding: 2px 10px; border-radius: 3px; color: #fff; font-weight: bold; font-size: 0.85em; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .get { background: #61affe; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .post { background: #49cc90; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .delete { background: #f93e3e; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .path { font-family: Consolas, Courier New, monospace; margin-left: 8px; font-weight: bold; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .desc { margin-top: 4px; color: #666; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    .version { color: #999; font-size: 0.9em; margin-bottom: 20px; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    hr { border: none; border-top: 1px solid #eee; margin: 40px 0; }')
$stream.Write([Environment]::NewLine)
$stream.Write('    footer { color: #999; font-size: 0.85em; }')
$stream.Write([Environment]::NewLine)
$stream.Write('  </style>')
$stream.Write([Environment]::NewLine)
$stream.Write('</head>')
$stream.Write([Environment]::NewLine)
$stream.Write('<body>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <h1>YLproxy API Documentation</h1>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <p class="version">Version: ' + $version + '</p>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <p>REST API for managing proxy configurations, testing connectivity, and controlling proxy lifecycle.</p>')
$stream.Write([Environment]::NewLine)
$stream.Write('')
$stream.Write([Environment]::NewLine)
$stream.Write('  <h2>Health</h2>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method get">GET</span><span class="path">/api/health</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Service health check endpoint</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('')
$stream.Write([Environment]::NewLine)
$stream.Write('  <h2>Proxies</h2>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method get">GET</span><span class="path">/api/proxies</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Retrieve all proxy entries</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method get">GET</span><span class="path">/api/proxies/{id}</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Retrieve a single proxy by ID</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method post">POST</span><span class="path">/api/proxies</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Create a new proxy entry</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method delete">DELETE</span><span class="path">/api/proxies/{id}</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Delete a proxy entry by ID</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method post">POST</span><span class="path">/api/proxies/{id}/test</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Test proxy connectivity</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method post">POST</span><span class="path">/api/proxies/{id}/start</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Start a proxy</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method post">POST</span><span class="path">/api/proxies/{id}/stop</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Stop a proxy</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('')
$stream.Write([Environment]::NewLine)
$stream.Write('  <h2>Stats</h2>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <div class="endpoint">')
$stream.Write([Environment]::NewLine)
$stream.Write('    <span class="method get">GET</span><span class="path">/api/stats</span>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <div class="desc">Get dashboard statistics</div>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </div>')
$stream.Write([Environment]::NewLine)
$stream.Write('')
$stream.Write([Environment]::NewLine)
$stream.Write('  <hr>')
$stream.Write([Environment]::NewLine)
$stream.Write('  <footer>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <p>Generated by YLproxy CI/CD Pipeline</p>')
$stream.Write([Environment]::NewLine)
$stream.Write('    <p>Source: <a href="https://github.com/lygg6699/YLproxy">github.com/lygg6699/YLproxy</a></p>')
$stream.Write([Environment]::NewLine)
$stream.Write('  </footer>')
$stream.Write([Environment]::NewLine)
$stream.Write('</body>')
$stream.Write([Environment]::NewLine)
$stream.Write('</html>')
$stream.Write([Environment]::NewLine)
$stream.Close()

Write-Host "[docs] Generated: $OutputDir/index.html"
Write-Host "[docs] Documentation generation complete."

